#!/usr/bin/env bash
# ============================================================
#  TelStore Telegram Bot — interactive server installer
#  ------------------------------------------------------------
#  Runs the bot as a 24/7 background service (systemd).
#  Asks the OWNER for their real credentials (Telegram bot
#  token, crypto wallet, NOWPayments API key) and builds the
#  .env from those answers — no manual editing needed.
#
#  Tested on Ubuntu / Debian (any Python 3.8+).
#
#  USAGE:
#    1) Copy the whole TelStore/ folder to your server
#       (scp -r TelStore user@server:~/)
#    2) cd TelStore && bash scripts/deploy_server.sh
#    3) Answer the prompts with YOUR OWN values.
#
#  The script:
#     - checks/installs python3
#     - prompts for token, wallet, NOWPayments key, owner id
#     - writes .env from your answers (replaces an old one)
#     - installs a systemd service named 'telstore'
#     - starts it now and enables it to start on boot
#
#  Useful commands:
#     systemctl status telstore          # is it running?
#     journalctl -u telstore -f          # live logs
#     systemctl restart telstore         # restart the bot
# ============================================================
set -e

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
say(){ echo -e "${GREEN}[telstore]${NC} $*"; }
warn(){ echo -e "${YELLOW}[warn]${NC} $*"; }
err(){ echo -e "${RED}[error]${NC} $*"; exit 1; }
prompt(){ echo -e "${GREEN}?${NC} $*"; }

# --- 1. locate project root (folder that contains scripts/) ----------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
if [ ! -f "$SCRIPT_DIR/bot.py" ]; then
  warn "bot.py not found next to this script; expecting TelStore/scripts/bot.py"
fi
say "Project root: $ROOT"

# --- 2. python3 ------------------------------------------------------------
if command -v python3 >/dev/null 2>&1; then
  PY="python3"; say "python3 found: $($PY --version 2>&1)"
else
  warn "python3 not found — installing..."
  if command -v apt-get >/dev/null 2>&1; then
    (apt-get update -y && apt-get install -y python3) 2>&1 | tail -2
  else
    err "No apt-get. Please install Python 3.8+ manually, then re-run."
  fi
fi

# --- 3. interactive prompts (buyer's OWN values) ---------------------------
say "Now tell me your OWN values. These are saved to .env so the bot"
say "works with YOUR wallet, YOUR NOWPayments account and YOUR bot."

prompt "Telegram bot token (from @BotFather):"
read -r BOT_TOKEN
if [ -z "$BOT_TOKEN" ]; then err "Bot token is required. Run again and paste it."; fi

prompt "Your Telegram chat_id (owner, from @userinfobot):"
read -r OWNER_ID
if [ -z "$OWNER_ID" ]; then err "Owner chat_id is required."; fi

prompt "Your crypto wallet address (EVM, for manual BSC/ETH/Polygon payments):"
read -r WALLET
if [ -z "$WALLET" ]; then
  warn "Wallet empty — manual network buttons will stay disabled."
  WALLET=""
fi

prompt "NOWPayments API key (optional — leave empty to disable card/crypto checkout):"
read -r NP_KEY
if [ -z "$NP_KEY" ]; then
  warn "NOWPayments key empty — the automatic checkout button will be hidden."
fi

# --- 4. write .env from answers -------------------------------------------
ENV_FILE="$ROOT/.env"
cat > "$ENV_FILE" <<EOF
# TelStore Bot — configuration (generated by deploy_server.sh)
# This .env was built from the answers you gave during install.
# You can edit it later and run: systemctl restart telstore

# Telegram bot
TELEGRAM_BOT_TOKEN=$BOT_TOKEN
TELEGRAM_CHAT_ID=$OWNER_ID

# Manual crypto payments (BSC / Ethereum / Polygon)
CRYPTO_ADDRESS=$WALLET

# NOWPayments automatic checkout (card + crypto)
NOWPAYMENTS_API_KEY=$NP_KEY

# Price & owner
PRICE_USD=5
OWNER_CHAT_ID=$OWNER_ID

# Website & support (optional — set later from Telegram as owner)
WEBSITE_URL=
SUPPORT_URL=
EOF
chmod 600 "$ENV_FILE"
say "Written .env with your settings."

# --- 5. sudo helper -------------------------------------------------------
run_root() {
  if [ "$(id -u)" = "0" ]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    err "Need root to $1. Run as root or install sudo."
  fi
}

# --- 6. systemd service ---------------------------------------------------
SERVICE_NAME="telstore"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
RUN_BIN="$SCRIPT_DIR/run_bot.sh"

# create a tiny run script (so systemd uses the right python)
cat > "$RUN_BIN" <<EOF
#!/usr/bin/env bash
cd "$ROOT/scripts"
exec $PY -u bot.py
EOF
chmod +x "$RUN_BIN"

cat > /tmp/telstore.service <<EOF
[Unit]
Description=TelStore Telegram Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$ROOT/scripts
ExecStart=$RUN_BIN
Restart=always
RestartSec=5
EnvironmentFile=$ENV_FILE

[Install]
WantedBy=multi-user.target
EOF

run_root cp /tmp/telstore.service "$SERVICE_FILE"
rm -f /tmp/telstore.service

run_root systemctl daemon-reload
run_root systemctl enable "$SERVICE_NAME" >/dev/null 2>&1
run_root systemctl restart "$SERVICE_NAME"

# --- 7. report ------------------------------------------------------------
sleep 3
if run_root systemctl is-active --quiet "$SERVICE_NAME"; then
  say "✅ Bot service is RUNNING."
  say "   Status : systemctl status $SERVICE_NAME"
  say "   Logs   : journalctl -u $SERVICE_NAME -f"
  say "   Restart: systemctl restart $SERVICE_NAME"
  say "The bot will auto-start on every boot."
else
  err "Service did not start. See: journalctl -u $SERVICE_NAME -n 50"
fi